name: snoozio
description: "Snoozio is more than just a sleep app, it is your nightly guide to rest, balance, and renewal. Designed with a calming nocturnal theme, Snoozio takes you on a 30-day journey toward better sleep, offering personalized care plans based on whether your struggles are mild, moderate, or severe. Each night becomes easier as youâ€™re gently guided by soothing reminders, relaxing soundscapes, mindful exercises, and uplifting quotes that inspire consistency and positivity. With progress tracking, smart alarms, and a built-in sleep diary, Snoozio doesnâ€™t just help you fall asleepâ€”it enables you to reimagine your relationship with rest, creating habits that last long after the program ends."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  zhi_starry_sky: ^0.0.2
  easy_dynamic_theme: ^2.3.1
  firebase_auth: ^6.1.0
  google_sign_in: ^7.1.1
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.2
  curved_navigation_bar: ^1.0.6
  hugeicons: ^1.1.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5
  permission_handler: ^11.1.0
  timezone: ^0.9.4
  url_launcher: ^6.3.2
  audioplayers: ^5.2.1
  firebase_messaging: ^16.0.4
  android_alarm_manager_plus: ^5.0.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.3
  file_picker: ^10.3.6
  vibration: ^3.1.4
  restart_app: ^1.2.1
  confetti: ^0.8.0
  flutter_to_pdf: ^0.4.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Squircle Snoozio.png"
  image_path_android: "assets/icon/Squircle Snoozio.png"

flutter:
  assets:
    - assets/icon/
    - assets/alarm/
    - assets/audio/

  uses-material-design: true